#encoding: utf-8
City.create(name:'Волгоград') 
City.create(name:'Воронеж') 
City.create(name:'Екатеринбург') 
City.create(name:'Ижевск') 
City.create(name:'Казань') 
City.create(name:'Краснодар') 
City.create(name:'Красноярск') 
City.create(name:'Москва') 
City.create(name:'Нижний Новгород') 
City.create(name:'Новосибирск') 
City.create(name:'Омск') 
City.create(name:'Пермь') 
City.create(name:'Ростов-на-Дону') 
City.create(name:'Самара') 
City.create(name:'Санкт-Петербург') 
City.create(name:'Саратов') 
City.create(name:'Тольятти') 
City.create(name:'Тюмень') 
City.create(name:'Ульяновск') 
City.create(name:'Уфа') 
City.create(name:'Челябинск') 
