# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  host: mysql2.locum.ru
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: igel84_sravnim17
  username: igel84_sravnim17
  password: k1l1zGRp

production:
  host: mysql2.locum.ru
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: igel84_sravnim17
  username: igel84_sravnim17
  password: k1l1zGRp